spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:native}

  data:
    mongodb:
      auto-index-creation: true
      database: amigoscode
      host: localhost
      port: 27017

server:
  port: 8080

springdoc:
  api-docs:
    enabled: true
    path: /api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui.html