server:
  port: 8080


spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:-native}
  datasource:
    url: jdbc:postgresql://luurzShnw0la2jF9cR3x@containers-us-west-165.railway.app:6190/railway
    username: ${PGUSER}
    password: ${PGPASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true
  main:
    web-application-type: servlet

springdoc:
  show-actuator: true
  api-docs:
      path: /api-docs
  swagger-ui:
      path: /