version: '3.7'

services:
  api:
    container_name: api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      DB_USERNAME: ${DB_USERNAME:-root}
      DB_PASSWORD: ${DB_PASSWORD:-@Potter77}
    networks:
      mssql-spring:

  db:
    container_name: db
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: '@Potter77'
      MYSQL_DATABASE: spring_db
    ports:
      - "3306:3306"
    networks:
      mssql-spring:

networks:
  mssql-spring: